version: "3"
services:
    proxy:
        build: ./nginx
        container_name: learningferry_proxy
        volumes:
            - ./nginx/certs/:/etc/ssl/private
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            - /var/log/nginx:/var/log/nginx
        depends_on: 
            - api
            - web
        ports:
            - 80:80
            - 443:443
        network_mode: host
    web:
        build: ../learningferry.client
        volumes:
               - ../learningferry.client:/ng-app
        container_name: learningferry_web     
        ports: 
             - 4200:4200           
             - 49153:49153       
        command: "ng serve --disableHostCheck"
        network_mode: host

    api:
        build: ../learningferry.server
        container_name: learningferry.server
        volumes:
            - ../learningferry.server:/app
        ports:
            - 5000:5000
        environment:
            - NODE_ENV=dev
        command:  "npm run dev"
        depends_on:
            - db
        network_mode: host

    db:
        image: mongo:4.1
        container_name: learningferry_db
        volumes:
            - "./mongo_latest_data:/data/db"
        ports:
             - 27018:27018
        network_mode: host

networks:
    default:
        external:
          name: "host"